### ISSUE TITLE
Respect invisibility mode

### ISSUE THREAD

**Issue by olabini** [otrv4/pidgin-otrng#68] opened 2018-09-13 11:57 UTC
See https://bugs.otr.im/plugins/pidgin-otr/issues/106 for reference

**Comment by olabini** [comment] 2019-03-10 23:42
Hopefully should be easy.

**Comment by peterpalau** [comment] 2019-08-06 14:09
_I publishing this comment here to have registered as we go forward with this._

We need to check how to get the invisible mode working with the [XMPP Server](https://xmpp.org/extensions/xep-0186.html), maybe using another service like a mirror, I don't know if we can use XMPP and IRC together, because IRC supports invisible mode.

**Comment by peterpalau** [comment] 2019-08-06 20:22
We should skip this issue for now because the `invisible` mode is not standardized **right now** in the `XMPP` protocol or at least they don't have a final solution that can be implemented by the most used IM clients.

The protocol have some specifications for the `invisible presence` like:

- __DEPRECATED__ [XEP-0018: Invisible Presence](https://xmpp.org/extensions/xep-0018.html)
- __DEPRECATED__ [XEP-0186: Invisible Command](https://xmpp.org/extensions/xep-0186.html)
- __DEPRECATED__ [XEP-0016: Privacy Lists](https://xmpp.org/extensions/xep-0016.html)
- __DRAFT__ [XEP-0191: Blocking Command](https://xmpp.org/extensions/xep-0191.html) the current version is **1.3** with date **2015-03-12**.

Anyway, in our case Pidgin don't support `invisible` mode using a `XMPP` server (like `prosody` or `ejabberd`) and that makes it more difficult for us to reproduce this issue.

For that reason we should close this issue at least until Pidgin supports `invisible` mode for `XMPP`.

__References__:

- [Protocols Supported by ejabberd](https://www.process-one.net/en/ejabberd/protocols/)
- [XMPP Extensions (XEPs) supported in Prosody](https://prosody.im/doc/xeplist)
- [Support XMPP Invisibility in Pidgin](https://developer.pidgin.im/ticket/4509)
- [[XMPP] Invisible mode violating standard in Pidgin](https://developer.pidgin.im/ticket/4322)
- [Invisible mode doesn't work in Jabber using Pidgin](https://developer.pidgin.im/ticket/1525)
- [Supported XEPs in Pidgin](https://developer.pidgin.im/wiki/SupportedXEPs)

**Comment by claucece** [comment] 2019-08-07 15:03
Perfect! Thanks @peterpalau !

**Closed by claucece** 2019-08-07 15:03 UTC
Labels: bug, importance medium
