### ISSUE TITLE
Can we respect "Hide New IM conversation" better

### ISSUE THREAD

**Issue by olabini** [otrv4/pidgin-otrng#60] opened 2018-09-13 11:41 UTC
See https://bugs.otr.im/plugins/pidgin-otr/issues/142

**Comment by MauroVelasco** [comment] 2019-06-27 17:26
I reproduced this issue in the following way:

After configure the "Hide new IM conversations as: Always" in the recipient

![issue_60_message2](https://user-images.githubusercontent.com/2516223/60286538-54392d00-98d5-11e9-84c9-037af74dbd51.png)

The messages are still shown at the top of window as shows:

![issue_60_message1](https://user-images.githubusercontent.com/2516223/60286716-b4c86a00-98d5-11e9-9e4d-4c8fa83c1254.png)

In the tests, the main window with the conversation is not shown. Also notice the states: Never and When Away, don't provide any action.

**Comment by claucece** [comment] 2019-07-01 11:47
Mmm.. very interesting.. Let's discuss this week.

**Comment by MauroVelasco** [comment] 2019-07-02 20:36
Hi @claucece, just to add more information:

With @Cris2760 we observed the following behavior:

Linux Mint
   * The last release of pidgin is 2.12.0
   * Is required install libnotify popups plugin to show the System Tray Icon
   * The option Tools/Preferences/System Tray Icon, is not being respected, the popup is shown indistinctly of the state configured (Always, On Unread Message, Never) 
  * The system tray message (top message) is shown always since the second message received, not when the conversation start
   * The option Tools/Preferences/Hide new IM conversations (Always, When Away, Never), respect the states configured.
  * We didn't find any case where the conversation window overlaps the actual window

Linux Ubuntu
   * The last release of pidgin is 2.13.0
   * The plugin libnotify is installed by default
   * The option Tools/Preferences/System Tray Icon, is not being respected, the popup is shown indistinctly of the state configured (Always, On Unread Message, Never) 
* The system tray message (top message) is shown always since the second message received, not when the conversation start
   * The option Tools/Preferences/Hide new IM conversations (Always, When Away, Never), respect the states configured.
  * We didn't find any case where the conversation window overlaps the actual window

**Comment by claucece** [comment] 2019-07-03 00:46
Hey!

I understand now the issue ;) So, the problem is not the notification; but rather the window itself. Usually what happens is:

Alice has configured 'Hide new IM conversations' to 'Always'. If Bob starts a conversation with her (not OTR), the conversation window does not show up unless it is clicked. 

In the case of OTR:

Alice has configured 'Hide new IM conversations' to 'Always'. If Bob starts a conversation with her (OTR), the conversation window does show up. 

Let's check this tomorrow.

**Comment by MauroVelasco** [comment] 2019-07-08 21:20
Hey @claucece, @peterpalau regarding this, the function used to recover a property from prefs.xml is `purple_prefs_get_string` and the property can be loaded using the path of element like `/pidgin/conversations/im/hide_new`

Example:
`purple_prefs_get_string("/pidgin/conversations/im/hide_new")` can return the value `always` or the property configured.

**Comment by claucece** [comment] 2019-07-09 00:14
Hi, @MauroVelasco 

> Hey @claucece, @peterpalau regarding this, the function used to recover a property from prefs.xml is purple_prefs_get_string and the property can be loaded using the path of element like /pidgin/conversations/im/hide_new

Oh, awesome! Do we know if this is an exposed function? It does not seem so... but I can be wrong ;)

I looked at the code, and it seems what you might want to look at is the `otrng_gtk_dialog_new_purple_conv` function on the gtk-dialog file...

**Comment by MauroVelasco** [comment] 2019-07-09 02:03
Hi, @claucece,

> Hi, @MauroVelasco
> 
> > Hey @claucece, @peterpalau regarding this, the function used to recover a property from prefs.xml is purple_prefs_get_string and the property can be loaded using the path of element like /pidgin/conversations/im/hide_new
> 
> Oh, awesome! Do we know if this is an exposed function? It does not seem so... but I can be wrong ;)

I think so, I did a test using this function to get a preference from prefs.xml and worked well. The API can be found on:

`https://developer.pidgin.im/doxygen/2.5.0/html/prefs_8h.html`

> 
> I looked at the code, and it seems what you might want to look at is the `otrng_gtk_dialog_new_purple_conv` function on the gtk-dialog file...

Great, thank you, I'll check this function.

**Comment by claucece** [comment] 2019-07-17 11:30
I think this is now done.. closing this ;)

**Closed by claucece** 2019-07-17 11:30 UTC
Labels: bug, importance medium
